system:
  version: "v1.0.0"

database:
  mysql:
    host: "192.168.2.1"
    port: "3306"
    driver: "mysql"
    dbname: "im_serve"
    user: "gan"
    password: "ghj201711@"
  redis:
    host: "192.168.2.2"
    port: "3456"
    dbname: "im_serve"
    password: "ghj201711@"
  mongodb:
    host: "192.168.2.3"
    port: "1234"
    dbname: "im_serve"
  minio:
    host: "192.168.2.3"
    port: "9000"
    driver: "mysql"
    dbname: "minio"
